#!/bin/csh
if(-e A) then
grep -A 800 Master A | grep _lay | awk '{print$2}' > A_1
endif
if(-e B) then
grep -A 800 Master B | grep _lay | awk '{print$2}' > B_1
endif
if(-e C) then
grep -A 800 Master C | grep _lay | awk '{print$2}' > C_1
endif
if(-e D) then
grep -A 800 Master D | grep _lay | awk '{print$2}' > D_1
endif
if(-e E) then
grep -A 800 Master E | grep _lay | awk '{print$2}' > E_1
endif
if(-e F) then
grep -A 800 Master F | grep _lay | awk '{print$2}' > F_1
endif
if(-e G) then
grep -A 800 Master G | grep _lay | awk '{print$2}' > G_1
endif
if(-e H) then
grep -A 800 Master H | grep _lay | awk '{print$2}' > H_1
endif
if(-e I) then
grep -A 800 Master I | grep _lay | awk '{print$2}' > I_1
endif
if(-e J) then
grep -A 800 Master J | grep _lay | awk '{print$2}' > J_1
endif
if(-e K) then
grep -A 800 Master K | grep _lay | awk '{print$2}' > K_1
endif
if(-e L) then
grep -A 800 Master L | grep _lay | awk '{print$2}' > L_1
endif
if(-e M) then
grep -A 800 Master M | grep _lay | awk '{print$2}' > M_1
endif
if(-e N) then
grep -A 800 Master N | grep _lay | awk '{print$2}' > N_1
endif
if(-e O) then
grep -A 800 Master O | grep _lay | awk '{print$2}' > O_1
endif
if(-e P) then
grep -A 800 Master P | grep _lay | awk '{print$2}' > P_1
endif
if(-e Q) then
grep -A 800 Master Q | grep _lay | awk '{print$2}' > Q_1
endif
if(-e R) then
grep -A 800 Master R | grep _lay | awk '{print$2}' > R_1
endif
if(-e S) then
grep -A 800 Master S | grep _lay | awk '{print$2}' > S_1
endif
if(-e T) then
grep -A 800 Master T | grep _lay | awk '{print$2}' > T_1
endif
if(-e U) then
grep -A 800 Master U | grep _lay | awk '{print$2}' > U_1
endif
if(-e V) then
grep -A 800 Master V | grep _lay | awk '{print$2}' > V_1
endif
if(-e W) then
grep -A 800 Master W | grep _lay | awk '{print$2}' > W_1
endif
if(-e X) then
grep -A 800 Master X | grep _lay | awk '{print$2}' > X_1
endif
if(-e Y) then
grep -A 800 Master Y | grep _lay | awk '{print$2}' > Y_1
endif
if(-e Z) then
grep -A 800 Master Z | grep _lay | awk '{print$2}' > Z_1
endif
rename _1 '' *

